spring:
    application:
      name: service-new-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8081
server:
  port: 8198
#网管test
zuul:
  routes:
    api-a:
      path: /api-user/**
      service-id: service1
      sensitive-headers:
    api-b:
      path: /api-order/**
      service-id: service4


